apiVersion: skaffold/v4beta10
kind: Config
metadata:
  name: mplace
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: mplace-image
      jib: {}

manifests:
  rawYaml:
    - deployment.yaml
portForward:
  - resourceType: service
    resourceName: mplace-image
    port: 8080
